name = "KwdefHelpers"
uuid = "80d9ef48-13f8-4f87-9333-d4c97b041895"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"

[compat]
AccessorsExtra = "0.1.81"
julia = "1.9"
