name = "KwdefHelpers"
uuid = "80d9ef48-13f8-4f87-9333-d4c97b041895"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"

[compat]
Accessors = "0.1.38"
julia = "1.9"
